name: Integration file

on: 
    push: 
        branches: [main]
    pull_request: 
        branches: [main]

jobs:
    api_build:
        runs-on: ubuntu-latest

        steps:
            - name: Install dependencies
              run: echo test
